### ISSUE TITLE
Add details on how to launch demo

### ISSUE THREAD

**Issue by barrymoore** [CDDRC/cddrc.github.io#1]
Need a blog post to describe the demo project and how to access/explore it

**Comment by anderspitman** [comment]
@barrymoore since we don't have any blog posts yet, when you want to add the page, I'd say probably just create a `/blog/blog-post-name/index.html` file with the content you want, if that sounds good. Let me know if you run into any trouble using tuplates to include the head and footer.

**Comment by barrymoore** [comment]
Thanks, I'll do that.  Do we have the ability to add that 'Blog roll' of 3 most recent posts to the bottom of the home page?  If that isn't a quick update, then we can that to a later release and I'll just make up a 'Demo' page for this release for Joe's presentation.

**Comment by anderspitman** [comment]
I guess to be more specific, would it make more sense to work on that or the people page?

**Comment by barrymoore** [comment]
Probably makes more sense to do the people page, I can add the project demo on it's own page for now and add a link to that to the navbar.

**Comment by barrymoore** [comment]
Done
