### ISSUE TITLE
Switch to a real static site generator?

### ISSUE THREAD

**Issue by anderspitman** [CDDRC/cddrc.github.io#12]
@barrymoore, how would you feel about moving away from tuplates? It was a homegrown experiment that we're already outgrowing. I need something more powerful for implementing the people page because of the duplication. I feel like a real SSG would make more sense. I've switched over to [Eleventy](https://www.11ty.dev/docs/) in this branch:

https://github.com/CDDRC/cddrc.github.io/tree/switch-to-eleventy

Eleventy is nice because you can use pretty much any templating engine you want, including Liquid which is what Jekyll uses and what I'm currently using. 

You will need to be able to have node/npm in order to use it, but the commands are very simple.

**Comment by anderspitman** [comment]
Awesome, I've been really happy with it.

**Comment by barrymoore** [comment]
OK, thanks.

**Comment by anderspitman** [comment]
@barrymoore deployment should be automatic now whenever something is push to master. Takes less than 30s to run. Let me know if you have any issues with it.
